simulation_compositions:
  simulations:
    - simulation_config: "../../inputs/simulation/large_simulation_room.yaml"
      mission_configs:
        - "../../inputs/mission/large_mission_room.yaml"

  drone_configs:
    - "../../inputs/drone/drone_small.yaml"

  lidar_configs:
    - "../../inputs/lidar/lidar_short.yaml"
