simulation_compositions:
  simulations:
    - simulation_config: "../../inputs/simulation/small_simulation_out.yaml"
      mission_configs:
        - "../../inputs/mission/small_mission_out.yaml"

  drone_configs:
    - "../../inputs/drone/drone_small.yaml"

  lidar_configs:
    - "../../inputs/lidar/lidar_short.yaml"
