simulation_compositions:
  simulations:
    - simulation_config: "simulation/open.yaml"
      mission_configs:
        - "mission/tiny.yaml"
        - "mission/short.yaml"

  drone_configs:
    - "drone/drone.yaml"

  lidar_configs:
    - "lidar/lidar.yaml"
    - "lidar/lidar_tiny.yaml"
